### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by superman-enamy** [Kourva/AwesomeChatGPTBot#2]
When sending any promt to bot bot reply :
That's and error! Try again.

**Comment by Kourva** [comment]
Hi @superman-enamy 

It seems most of the websites that use ChatGPT are down, which is why the bot is not working. I will Google it and find a new website to use as soon as possible!

Thanks for your report.

**Comment by Kourva** [comment]
Source code has been updated!
Read the installation and re-install the tool again.

**Comment by superman-enamy** [comment]
> Source code has been updated! Read the installation and re-install the tool again.

When i run the bot and sebd any promt to bot then bot not respond.
Log: The Bot is online (id: 6145433381)...
2023-08-28 22:46:48,371 (__init__.py:1083 MainThread) ERROR - TeleBot: "Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: message text is empty"
2023-08-28 22:46:48,371 (__init__.py:1085 MainThread) ERROR - TeleBot: "Exception traceback:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/telebot/__init__.py", line 1074, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "/usr/local/lib/python3.10/dist-packages/telebot/util.py", line 147, in raise_exceptions
    raise self.exception_info
  File "/usr/local/lib/python3.10/dist-packages/telebot/util.py", line 90, in run
    task(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/telebot/__init__.py", line 6788, in _run_middlewares_and_handler
    result = handler['function'](message)
  File "/content/AwesomeChatGPTBot/main.py", line 242, in handle_messages
    GPTbot.edit_message_text(
  File "/usr/local/lib/python3.10/dist-packages/telebot/__init__.py", line 3826, in edit_message_text
    result = apihelper.edit_message_text(self.token, text, chat_id, message_id, inline_message_id, parse_mode,
  File "/usr/local/lib/python3.10/dist-packages/telebot/apihelper.py", line 1320, in edit_message_text
    return _make_request(token, method_url, params=payload, method='post')
  File "/usr/local/lib/python3.10/dist-packages/telebot/apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "/usr/local/lib/python3.10/dist-packages/telebot/apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: message text is empty
"

**Comment by Kourva** [comment]
@superman-enamy 

I run the bot and its working. when its say message text is empty, maybe problem is related to chat GPT API, maybe its not working on your IP address or its temporary down! so it will response with empty message and when bot is trying to send it to user, Telegram will not allow it due to empty response!

I will add more error handling to bot to make it better!

**Comment by Onair-santa** [comment]
![image](https://github.com/Kourva/AwesomeChatGPTBot/assets/42511409/e75bdca3-1ba3-4e95-b612-7202c5790dc0)
