### ISSUE TITLE
AttributeError: module 'titles' has no attribute 'welcome_2'

### ISSUE THREAD

**Issue by chelaxian** [Kourva/AwesomeChatGPTBot#26]
Hello! After last update I have error while run python code:

```
root@TG-GPT-bot:~/github/GPT/AwesomeChatGPTBot# python3 main.py 
The Bot is online (id: 6191756482) [Normal MODE]...
2023-12-03 17:19:21,313 (__init__.py:960 MainThread) ERROR - TeleBot: "Infinity polling exception: module 'titles' has no attribute 'welcome_2'"
2023-12-03 17:19:21,313 (__init__.py:962 MainThread) ERROR - TeleBot: "Exception traceback:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/telebot/__init__.py", line 955, in infinity_polling
    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "/usr/local/lib/python3.10/dist-packages/telebot/__init__.py", line 1043, in polling
    self.__threaded_polling(non_stop=non_stop, interval=interval, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "/usr/local/lib/python3.10/dist-packages/telebot/__init__.py", line 1118, in __threaded_polling
    raise e
  File "/usr/local/lib/python3.10/dist-packages/telebot/__init__.py", line 1074, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "/usr/local/lib/python3.10/dist-packages/telebot/util.py", line 147, in raise_exceptions
    raise self.exception_info
  File "/usr/local/lib/python3.10/dist-packages/telebot/util.py", line 90, in run
    task(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/telebot/__init__.py", line 6801, in _run_middlewares_and_handler
    result = handler['function'](message)
  File "/root/github/GPT/AwesomeChatGPTBot/main.py", line 71, in start_command_handler
    text=titles.welcome_2.format(user.get_name)
AttributeError: module 'titles' has no attribute 'welcome_2'
```

I look into titles.py and there is NO text 'welcome_2'. i suppose you need to fix titles.py and add to it all missing attributes.

**Comment by Kourva** [comment]
Hi @chelaxian,

I mistakenly uploaded the wrong file for `titles.py`, but I've corrected it now. You can use the bot, but if it doesn't respond, the API from fakeopen may not be working (as explained in the readme). I'll update the API if needed.

Thanks for your report.
